### ISSUE TITLE
点击头像怎么跳回主页啊

### ISSUE THREAD

**Issue by shuzang** [mowatermelon/hexo-theme-melon#1]
大神，总是忍不住点头像，但点击头像和下面的名字跳转的都是404，怎么改能让点击跳转回主页啊

**Comment by mowatermelon** [comment]
@shuzang  

> 可能情况

- 你推送到remote仓库文件是对的吗？
- 在最外层的config.yml配置的github page回调地址是正确的么？
- 你配置的回调地址是什么格式的？http还是SSH?
